// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJk9zGZODWfGK2BqS822gH0TPc3P7wH_U',
    appId: '1:867557802153:web:da8c4d0aeb4fba801e29b8',
    messagingSenderId: '867557802153',
    projectId: 'recipe-boss-6a961',
    authDomain: 'recipe-boss-6a961.firebaseapp.com',
    storageBucket: 'recipe-boss-6a961.appspot.com',
    measurementId: 'G-W1F9DBE53E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgUX6hqJ7effT0qAO51l-alklhVwr77Wg',
    appId: '1:867557802153:android:2f474244f9a6f1e81e29b8',
    messagingSenderId: '867557802153',
    projectId: 'recipe-boss-6a961',
    storageBucket: 'recipe-boss-6a961.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYGmWq2sTAOsZMU3IiUtDgz-AYsnIV-KU',
    appId: '1:867557802153:ios:8c3d78901d0cafd41e29b8',
    messagingSenderId: '867557802153',
    projectId: 'recipe-boss-6a961',
    storageBucket: 'recipe-boss-6a961.appspot.com',
    iosBundleId: 'com.example.projectweek1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYGmWq2sTAOsZMU3IiUtDgz-AYsnIV-KU',
    appId: '1:867557802153:ios:e1228828e6365cd11e29b8',
    messagingSenderId: '867557802153',
    projectId: 'recipe-boss-6a961',
    storageBucket: 'recipe-boss-6a961.appspot.com',
    iosBundleId: 'com.example.projectweek1.RunnerTests',
  );
}
